name: Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn

      - name: Solidity Tests
        run: yarn coverage

      - name: Test Coverage Check
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
        with:
          coverage-file: coverage/lcov.info
          minimum-coverage: 80
