name: Tests

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Install Dependencies
        run: yarn

      - name: Solidity Tests
        run: npx hardhat test
